# Plan-time gate for every production image variable. Task definitions remain
# owned by their existing stacks; this file rejects unsafe inputs before any
# task-definition diff can be planned or applied.

variable "image_release_receipt_catalog" {
  description = "Exact immutable S3 locators keyed by the signed receipt content SHA-256 claim ID."
  type = map(object({
    bucket               = string
    key                  = string
    version_id           = string
    signature_key        = string
    signature_version_id = string
  }))
  default = {}

  validation {
    condition = alltrue([
      for claim_id, reference in var.image_release_receipt_catalog :
      can(regex("^[0-9a-f]{64}$", claim_id)) &&
      reference.bucket == "teamagent-dev-image-release-evidence" &&
      can(regex(
        "^release-receipts/(mcp|openclaw)/[0-9a-f]{40}/${claim_id}\\.json$",
        reference.key,
      )) &&
      reference.signature_key == "${reference.key}.sig" &&
      can(regex("^[A-Za-z0-9._~+/=-]{1,1024}$", reference.version_id)) &&
      can(regex(
        "^[A-Za-z0-9._~+/=-]{1,1024}$",
        reference.signature_version_id,
      ))
    ])
    error_message = "image_release_receipt_catalog must be keyed by the receipt content SHA-256 and contain only exact immutable mcp/openclaw S3 locators."
  }
}

variable "image_release_consumer_receipt_bindings" {
  description = "Consumer ID to signed receipt content SHA-256 claim ID bindings. Shared claims are allowed."
  type        = map(string)
  default     = {}

  validation {
    condition = alltrue([
      for consumer_id, claim_id in var.image_release_consumer_receipt_bindings :
      can(regex("^[a-z0-9][a-z0-9_-]*$", consumer_id)) &&
      can(regex("^[0-9a-f]{64}$", claim_id))
    ])
    error_message = "image_release_consumer_receipt_bindings must map canonical consumer IDs to lowercase SHA-256 claim IDs."
  }
}

variable "image_deployment_consumer_manifest" {
  description = "Ephemeral exact-eight live/before/after consumer manifest generated by the guarded saved-plan workflow; never persist in tfvars."
  type        = any
  default     = null
  nullable    = true

  validation {
    condition = var.image_deployment_consumer_manifest == null ? true : try(
      sort(keys(var.image_deployment_consumer_manifest)) == sort([
        "schema_version",
        "registry_sha256",
        "mode",
        "consumers",
      ]) &&
      var.image_deployment_consumer_manifest.schema_version == 1 &&
      can(regex(
        "^[0-9a-f]{64}$",
        var.image_deployment_consumer_manifest.registry_sha256,
      )) &&
      contains(
        ["receipt-required", "no-image-transition"],
        var.image_deployment_consumer_manifest.mode,
      ) &&
      length(var.image_deployment_consumer_manifest.consumers) == 8,
      false,
    )
    error_message = "image_deployment_consumer_manifest must be the exact schema-v1, exact-eight receipt-required/no-image-transition manifest."
  }
}

variable "image_deployment_intent_id" {
  description = "Ephemeral UUIDv4 generated only by terraform_runtime_guard.sh plan; never persist in tfvars."
  type        = string
  default     = ""

  validation {
    condition = (
      var.image_deployment_intent_id == "" ||
      can(regex(
        "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
        var.image_deployment_intent_id,
      ))
    )
    error_message = "image_deployment_intent_id must be blank or a lowercase UUIDv4."
  }
}

variable "image_release_shared_generation_ledger" {
  description = "Optional non-secret HMAC-worker ledger snapshot bound into the one-time image release intent. The HMAC stack owns the table and live preflight."
  type = object({
    table_arn     = string
    generation    = number
    high_water_t0 = string
    stage         = string
  })
  default  = null
  nullable = true

  validation {
    condition = var.image_release_shared_generation_ledger == null ? true : (
      can(regex(
        "^arn:aws:dynamodb:ap-northeast-1:718959508629:table/[A-Za-z0-9_.-]{3,255}$",
        var.image_release_shared_generation_ledger.table_arn,
      )) &&
      var.image_release_shared_generation_ledger.generation >= 0 &&
      var.image_release_shared_generation_ledger.generation <= 9223372036854775807 &&
      var.image_release_shared_generation_ledger.generation == floor(
        var.image_release_shared_generation_ledger.generation
      ) &&
      can(regex(
        "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$",
        var.image_release_shared_generation_ledger.high_water_t0,
      )) &&
      can(formatdate(
        "YYYY-MM-DD'T'hh:mm:ss'Z'",
        var.image_release_shared_generation_ledger.high_water_t0,
      )) &&
      can(regex(
        "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$",
        var.image_release_shared_generation_ledger.stage,
      ))
    )
    error_message = "image_release_shared_generation_ledger must contain only a fixed-account table ARN, nonnegative integer generation, RFC3339 high_water_t0, and canonical stage."
  }
}

data "external" "deployment_consumer_registry_sha256" {
  program = [
    "python3",
    "${path.module}/image_release_context.py",
    "registry-sha256",
  ]
}

locals {
  deployment_consumer_registry = jsondecode(
    file("${path.module}/../codebuild/image_deployment_consumers.json")
  )
  # The Python release-chain canonicalizer is authoritative. Terraform must
  # consume that digest instead of independently approximating canonical JSON.
  deployment_consumer_registry_sha256 = data.external.deployment_consumer_registry_sha256.result.sha256
  deployment_consumer_registry_by_id = {
    for consumer in local.deployment_consumer_registry.consumers :
    consumer.consumer_id => consumer
  }
  deployment_consumer_ids = toset(keys(local.deployment_consumer_registry_by_id))
  deployment_consumer_enabled = {
    mcp            = var.mcp_image != ""
    connect_web    = var.enable_connect_web && var.mcp_image != ""
    openclaw       = var.openclaw_image != ""
    canary         = var.enable_canary_health && var.mcp_image != ""
    ingest         = var.enable_ingest_schedule && var.mcp_image != ""
    morning_digest = var.enable_morning_digest && var.mcp_image != ""
    x_buzz_worker  = var.enable_x_research && var.x_buzz_image != ""
    tiktok_acquire = local.media_worker_enabled && local.media_worker_image != ""
  }
  deployment_expected_consumer_images = {
    mcp            = var.mcp_image
    connect_web    = var.mcp_image
    openclaw       = var.openclaw_image
    canary         = var.mcp_image
    ingest         = var.mcp_image
    morning_digest = var.mcp_image
    x_buzz_worker  = var.x_buzz_image
    tiktok_acquire = local.media_worker_image
  }
  deployment_contract_sha256 = {
    mcp      = filesha256("${path.module}/../codebuild/teamagent_core_media_release_contract.json")
    openclaw = filesha256("${path.module}/../codebuild/openclaw_bundle_contract.json")
  }
  deployment_contract_ready = {
    mcp = jsondecode(
      file("${path.module}/../codebuild/teamagent_core_media_release_contract.json")
    ).release.ready
    openclaw = jsondecode(
      file("${path.module}/../codebuild/openclaw_bundle_contract.json")
    ).release.ready
  }
  deployment_manifest_root_is_valid = (
    var.image_deployment_consumer_manifest != null &&
    try(
      sort(keys(var.image_deployment_consumer_manifest)) == sort([
        "schema_version",
        "registry_sha256",
        "mode",
        "consumers",
      ]) &&
      var.image_deployment_consumer_manifest.schema_version == 1 &&
      can(regex(
        "^[0-9a-f]{64}$",
        var.image_deployment_consumer_manifest.registry_sha256,
      )) &&
      contains(
        ["receipt-required", "no-image-transition"],
        var.image_deployment_consumer_manifest.mode,
      ) &&
      length(var.image_deployment_consumer_manifest.consumers) == 8,
      false,
    )
  )
  deployment_manifest_registry_is_exact = (
    local.deployment_manifest_root_is_valid &&
    try(
      var.image_deployment_consumer_manifest.schema_version == 1 &&
      var.image_deployment_consumer_manifest.registry_sha256 ==
      local.deployment_consumer_registry_sha256 &&
      length(local.deployment_consumer_registry.consumers) == 8 &&
      length(var.image_deployment_consumer_manifest.consumers) == 8 &&
      alltrue([
        for index, registry_consumer in local.deployment_consumer_registry.consumers :
        try(
          sort(keys(var.image_deployment_consumer_manifest.consumers[index])) == sort([
            "consumer_id",
            "terraform_task_definition_address",
            "ecs_family",
            "container_name",
            "activator",
            "release_repository",
            "receipt",
            "live",
            "before",
            "after",
          ]) &&
          var.image_deployment_consumer_manifest.consumers[index].consumer_id ==
          registry_consumer.consumer_id &&
          var.image_deployment_consumer_manifest.consumers[index].terraform_task_definition_address ==
          registry_consumer.terraform_task_definition_address &&
          var.image_deployment_consumer_manifest.consumers[index].ecs_family ==
          registry_consumer.ecs_family &&
          var.image_deployment_consumer_manifest.consumers[index].container_name ==
          registry_consumer.container_name &&
          var.image_deployment_consumer_manifest.consumers[index].activator ==
          registry_consumer.activator &&
          var.image_deployment_consumer_manifest.consumers[index].release_repository ==
          registry_consumer.release_repository &&
          var.image_deployment_consumer_manifest.consumers[index].receipt ==
          registry_consumer.receipt,
          false,
        )
      ]),
      false,
    )
  )
  deployment_manifest_structure_is_exact = (
    local.deployment_manifest_registry_is_exact &&
    try(
      alltrue([
        for consumer in var.image_deployment_consumer_manifest.consumers :
        alltrue([
          for phase in ["live", "before", "after"] :
          (
            try(
              sort(keys(consumer[phase])) == ["absent"] &&
              consumer[phase].absent == true,
              false,
            ) ||
            try(
              sort(keys(consumer[phase])) == sort([
                "image",
                "task_definition_arn",
                "task_definition",
                "activation",
              ]) &&
              sort(keys(consumer[phase].task_definition)) == sort([
                "container_definitions",
                "task_role_arn",
                "execution_role_arn",
                "network_mode",
                "cpu",
                "memory",
                "volumes",
              ]) &&
              (
                consumer.activator.type == "ecs_service" ?
                sort(keys(consumer[phase].activation)) == sort([
                  "desired_count",
                  "task_definition_arn",
                ]) :
                consumer.activator.type == "eventbridge_rule_ecs_target" ?
                sort(keys(consumer[phase].activation)) == sort([
                  "state",
                  "task_definition_arn",
                ]) :
                sort(keys(consumer[phase].activation)) == sort([
                  "event_source_mapping_enabled",
                  "task_definition_arn",
                ])
              ),
              false,
            )
          )
        ])
      ]),
      false,
    )
  )
  deployment_manifest_presence_is_exact = (
    local.deployment_manifest_structure_is_exact &&
    try(
      alltrue([
        for consumer in var.image_deployment_consumer_manifest.consumers :
        local.deployment_consumer_enabled[consumer.consumer_id] ?
        !try(consumer.after.absent, false) :
        try(
          consumer.live.absent == true &&
          consumer.before.absent == true &&
          consumer.after.absent == true,
          false,
        )
      ]),
      false,
    )
  )
  deployment_manifest_after_images_are_exact = (
    local.deployment_manifest_presence_is_exact ? alltrue([
      for consumer in var.image_deployment_consumer_manifest.consumers :
      !local.deployment_consumer_enabled[consumer.consumer_id] ? true : try(
        consumer.after.image ==
        local.deployment_expected_consumer_images[consumer.consumer_id] &&
        length(split("@sha256:", consumer.after.image)) == 2 &&
        (
          split("@sha256:", consumer.after.image)[0] ==
          "718959508629.dkr.ecr.ap-northeast-1.amazonaws.com/${consumer.release_repository}" ||
          (
            consumer.consumer_id == "tiktok_acquire" &&
            consumer.release_repository == "teamagent-media-worker" &&
            local.pre_media_cutover_sync &&
            consumer.after.image == local.pre_media_cutover_sync_image &&
            consumer.live == consumer.before &&
            consumer.before == consumer.after
          )
        ) &&
        can(regex(
          "^[0-9a-f]{64}$",
          split("@sha256:", consumer.after.image)[1],
        )),
        false,
      )
    ]) : false
  )
  deployment_receipt_required_consumer_ids = toset(
    local.deployment_manifest_presence_is_exact ? [
      for consumer in var.image_deployment_consumer_manifest.consumers :
      consumer.consumer_id
      if local.deployment_consumer_enabled[consumer.consumer_id] && (
        !can(consumer.before.image) ||
        try(
          consumer.before.image != consumer.after.image ||
          consumer.before.task_definition_arn !=
          consumer.after.task_definition_arn ||
          jsonencode(consumer.before.task_definition) !=
          jsonencode(consumer.after.task_definition) ||
          (
            consumer.activator.type == "ecs_service" ?
            consumer.before.activation.desired_count !=
            consumer.after.activation.desired_count :
            consumer.activator.type == "eventbridge_rule_ecs_target" ?
            consumer.before.activation.state != consumer.after.activation.state :
            consumer.before.activation.event_source_mapping_enabled !=
            consumer.after.activation.event_source_mapping_enabled
          ),
          true,
        )
      )
    ] : []
  )
  deployment_affected_consumer_ids = toset(
    local.deployment_manifest_presence_is_exact ? [
      for consumer in var.image_deployment_consumer_manifest.consumers :
      consumer.consumer_id
      if local.deployment_consumer_enabled[consumer.consumer_id] && (
        !can(consumer.before.image) ||
        try(
          consumer.before.image != consumer.after.image ||
          consumer.before.task_definition_arn !=
          consumer.after.task_definition_arn ||
          jsonencode(consumer.before.task_definition) !=
          jsonencode(consumer.after.task_definition) ||
          jsonencode(consumer.before.activation) !=
          jsonencode(consumer.after.activation),
          true,
        )
      )
    ] : []
  )
  deployment_binding_consumer_ids = toset(
    keys(var.image_release_consumer_receipt_bindings)
  )
  deployment_binding_consumers_are_exact = (
    length(setsubtract(
      local.deployment_binding_consumer_ids,
      local.deployment_consumer_ids,
    )) == 0 &&
    length(setsubtract(
      local.deployment_binding_consumer_ids,
      local.deployment_receipt_required_consumer_ids,
    )) == 0 &&
    length(setsubtract(
      local.deployment_receipt_required_consumer_ids,
      local.deployment_binding_consumer_ids,
    )) == 0
  )
  deployment_catalog_claim_ids = toset(
    keys(var.image_release_receipt_catalog)
  )
  deployment_bound_claim_ids = toset(
    values(var.image_release_consumer_receipt_bindings)
  )
  deployment_catalog_bindings_are_exact = (
    length(setsubtract(
      local.deployment_catalog_claim_ids,
      local.deployment_bound_claim_ids,
    )) == 0 &&
    length(setsubtract(
      local.deployment_bound_claim_ids,
      local.deployment_catalog_claim_ids,
    )) == 0
  )
  deployment_release_consumer_ids = toset(
    local.deployment_manifest_presence_is_exact ? [
      for consumer in var.image_deployment_consumer_manifest.consumers :
      consumer.consumer_id
      if local.deployment_consumer_enabled[consumer.consumer_id] && (
        var.image_deployment_consumer_manifest.mode == "no-image-transition" ||
        contains(local.deployment_affected_consumer_ids, consumer.consumer_id)
      )
    ] : []
  )
  deployment_release_pipelines = toset([
    for consumer_id in local.deployment_release_consumer_ids :
    local.deployment_consumer_registry_by_id[consumer_id].receipt.pipeline
  ])
  deployment_contract_bindings = {
    for pipeline, contract_sha256 in local.deployment_contract_sha256 :
    pipeline => contract_sha256
    if contains(local.deployment_release_pipelines, pipeline)
  }
  deployment_contract_ready_bindings = {
    for pipeline, ready in local.deployment_contract_ready :
    pipeline => ready
    if contains(local.deployment_release_pipelines, pipeline)
  }
  deployment_contracts_are_ready = (
    alltrue([
      for pipeline in local.deployment_release_pipelines :
      local.deployment_contract_ready[pipeline] == true
    ])
  )
  deployment_requested = (
    var.image_deployment_consumer_manifest != null ||
    length(var.image_release_receipt_catalog) != 0 ||
    length(var.image_release_consumer_receipt_bindings) != 0 ||
    anytrue([
      for image in values(local.deployment_expected_consumer_images) :
      image != ""
    ])
  )
  deployment_intent_is_valid = (
    !local.deployment_requested ||
    can(regex(
      "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      var.image_deployment_intent_id,
    ))
  )
  deployment_mcp_application_provenance = {
    mcp = {
      bucket                    = aws_s3_bucket.raw_files.bucket
      key                       = "codebuild/connect-web-app.html"
      version_id                = var.connect_app_html_s3_version_id
      sha256                    = var.connect_app_html_sha256
      vault_manifest_sha256     = var.connect_app_html_manifest_sha256
      build_inputs_sha256       = var.connect_app_html_build_inputs_sha256
      baked_fallback_version_id = local.canonical_baked_app_html_version_id
      baked_fallback_sha256     = local.canonical_baked_app_html_sha256
    }
  }
  deployment_application_provenance = {
    for pipeline, provenance in local.deployment_mcp_application_provenance :
    pipeline => provenance
    if contains(local.deployment_release_pipelines, pipeline)
  }
  # jsondecode preserves the generation number while allowing an empty object
  # until the separately owned HMAC ledger stack is integrated.
  deployment_shared_generation_ledger = jsondecode(
    var.image_release_shared_generation_ledger == null
    ? "{}"
    : jsonencode(var.image_release_shared_generation_ledger)
  )
  deployment_gate_preconditions = (
    local.deployment_manifest_structure_is_exact &&
    local.deployment_manifest_presence_is_exact &&
    local.deployment_manifest_after_images_are_exact &&
    local.deployment_binding_consumers_are_exact &&
    local.deployment_catalog_bindings_are_exact &&
    local.deployment_contracts_are_ready &&
    local.deployment_intent_is_valid
  )
  deployment_gate_query = {
    consumer_manifest_json         = jsonencode(var.image_deployment_consumer_manifest)
    receipt_catalog_json           = jsonencode(var.image_release_receipt_catalog)
    consumer_receipt_bindings_json = jsonencode(var.image_release_consumer_receipt_bindings)
    contracts_json                 = jsonencode(local.deployment_contract_bindings)
    contract_ready_json            = jsonencode(local.deployment_contract_ready_bindings)
    application_json               = jsonencode(local.deployment_application_provenance)
    shared_generation_ledger_json  = jsonencode(
      local.deployment_shared_generation_ledger
    )
    signing_key_arn      = aws_kms_key.image_attestor_signing.arn
    encryption_key_arn   = aws_kms_key.image_release_evidence.arn
    deployment_intent_id = var.image_deployment_intent_id
  }
}

data "external" "signed_image_release_gate" {
  count = local.deployment_requested && local.deployment_gate_preconditions ? 1 : 0

  program = [
    "bash",
    "${path.module}/../deploy/run_image_deployment_gate.sh",
    "terraform-gate",
  ]

  query = local.deployment_gate_query

  depends_on = [
    aws_dynamodb_table.image_deployment_intents,
    aws_iam_role_policy.image_deployment_gate,
  ]
}

resource "terraform_data" "production_image_release_gate" {
  input = {
    deployment_intent_id      = var.image_deployment_intent_id
    deployment_context_sha256 = try(data.external.signed_image_release_gate[0].result.deployment_context_sha256, "")
    receipt_claims_sha256     = try(data.external.signed_image_release_gate[0].result.receipt_claims_sha256, "")
    consumer_manifest         = var.image_deployment_consumer_manifest
    receipt_catalog           = var.image_release_receipt_catalog
    consumer_receipt_bindings = var.image_release_consumer_receipt_bindings
    deployment_mode = try(
      data.external.signed_image_release_gate[0].result.deployment_mode,
      "",
    )
    release_channels = try(
      jsondecode(data.external.signed_image_release_gate[0].result.release_channels_json),
      {},
    )
    application_provenance   = local.deployment_application_provenance
    shared_generation_ledger = local.deployment_shared_generation_ledger
    hmac_release_bindings    = local.hmac_release_intent_bindings
    deployment_gate_query    = local.deployment_gate_query
    receipt_authorization_expires_at = try(
      data.external.signed_image_release_gate[0].result.receipt_authorization_expires_at,
      "",
    )
  }

  # The reviewed UUID is the one-use replacement trigger. A wall-clock
  # plantimestamp would make an exact reviewed plan impossible to reproduce:
  # the review plan and the final saved plan would differ even when every
  # immutable input is unchanged. The trusted apply launcher still atomically
  # consumes this intent and any distinct bound receipt claims before
  # Terraform can start.
  triggers_replace = (
    local.deployment_requested ? [var.image_deployment_intent_id] : []
  )

  lifecycle {
    precondition {
      condition = (
        !local.deployment_requested ||
        (
          local.deployment_manifest_structure_is_exact &&
          local.deployment_manifest_presence_is_exact
        )
      )
      error_message = "Production image deployment consumer manifest is malformed or does not exactly match the code-owned registry and snapshot schema."
    }

    precondition {
      condition = (
        !local.deployment_requested ||
        local.deployment_contracts_are_ready
      )
      error_message = "Every pipeline affected by a production consumer change must have release.ready=true; empty receipt bindings and no-image-transition mode do not waive this requirement."
    }

    precondition {
      condition = (
        !local.deployment_requested ||
        (
          local.deployment_gate_preconditions &&
          try(
            data.external.signed_image_release_gate[0].result.verified == "true" &&
            data.external.signed_image_release_gate[0].result.deployment_mode ==
            var.image_deployment_consumer_manifest.mode,
            false,
          )
        )
      )
      error_message = "Production image consumers require the composed full saved-plan workflow, the exact code-owned eight-consumer manifest, a unique deployment intent, and either exact fresh signed consumer receipt bindings or a verifier-derived no-image-transition authorization."
    }
  }
}
