#!/usr/bin/env bash
# Create one full saved plan and conditionally reserve its unique deployment intent.
set -euo pipefail
umask 077

EXPECTED_BRANCH="dev"
EXPECTED_ORIGIN="git@github.com:noirelumiere00/TeamAgent.git"
EXPECTED_AUTOMATION_ARN="arn:aws:sts::718959508629:assumed-role/teamagent-dev-terraform-automation/teamagent-terraform-worker"
EXPECTED_REGION="ap-northeast-1"

die() {
  echo "FATAL: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
usage: plan_image_release.sh SAVED_PLAN [terraform plan arguments]

Creates a full saved plan with a unique image deployment intent, then
conditionally stores its plan/context/receipt binding in the durable intent
table. Runtime -target and caller-supplied intent overrides are forbidden.
EOF
}

reject_terraform_environment() {
  local variable
  while IFS= read -r variable; do
    [ -z "$variable" ] || die "pre-existing Terraform environment is forbidden: $variable"
  done < <(compgen -A variable TF_)
  unset variable
}

reject_terraform_environment
export TF_IN_AUTOMATION=1
export AWS_IGNORE_CONFIGURED_ENDPOINT_URLS=true
while IFS= read -r endpoint_variable; do
  unset "$endpoint_variable"
done < <(compgen -A variable AWS_ENDPOINT_URL)
unset endpoint_variable AWS_PROFILE AWS_DEFAULT_PROFILE
export AWS_DEFAULT_REGION="$EXPECTED_REGION" AWS_REGION="$EXPECTED_REGION"
export AWS_CONFIG_FILE=/dev/null AWS_SHARED_CREDENTIALS_FILE=/dev/null

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  "") usage >&2; exit 2 ;;
esac
plan_argument="$1"
shift
for argument in "$@"; do
  case "$argument" in
    -target|-target=*|--target|--target=*|-out|-out=*|--out|--out=*|\
    -state|-state=*|--state|--state=*|-state-out|-state-out=*|\
    -lock=false|--lock=false|-refresh=false|--refresh=false|\
    -refresh-only|--refresh-only|-destroy|--destroy|\
    -generate-config-out|-generate-config-out=*)
      die "runtime plans must be complete, locked, refresh-enabled full saved plans"
      ;;
    *image_deployment_intent_id*)
      die "the deployment intent is generated by this launcher"
      ;;
  esac
done
for tool in aws git python3 sha256sum terraform; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is required"
done
caller_arn="$(AWS_PAGER="" aws sts get-caller-identity --query Arn --output text)"
[ "$caller_arn" = "$EXPECTED_AUTOMATION_ARN" ] \
  || die "image release planning requires the exact trusted Terraform automation session"
unset caller_arn

case "$plan_argument" in
  */*) plan_parent="${plan_argument%/*}"; plan_name="${plan_argument##*/}" ;;
  *) plan_parent="."; plan_name="$plan_argument" ;;
esac
[ -n "$plan_name" ] && [ "$plan_name" != "." ] && [ "$plan_name" != ".." ] \
  || die "saved plan path is invalid"
plan_parent="$(cd -- "$plan_parent" && pwd -P)" \
  || die "saved plan parent directory does not exist"
plan_path="$plan_parent/$plan_name"
[ ! -e "$plan_path" ] || die "saved plan already exists"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
control_root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null)" \
  || die "planner is not inside the TeamAgent worktree"
case "$plan_path" in
  "$control_root"/*)
    die "saved plans must be stored outside the TeamAgent worktree"
    ;;
esac
[ -z "$(git -C "$control_root" status --porcelain=v1 --untracked-files=all --ignore-submodules=none)" ] \
  || die "TeamAgent control worktree is dirty"
[ "$(git -C "$control_root" symbolic-ref --quiet --short HEAD)" = "$EXPECTED_BRANCH" ] \
  || die "image deployment plans must be created from local dev"
[ "$(git -C "$control_root" config --get remote.origin.url)" = "$EXPECTED_ORIGIN" ] \
  || die "TeamAgent origin is not allowlisted"
git -C "$control_root" fetch --quiet --no-tags origin \
  "refs/heads/dev:refs/remotes/origin/dev" \
  || die "could not refresh origin/dev"
control_commit="$(git -C "$control_root" rev-parse HEAD)"
[ "$control_commit" = "$(git -C "$control_root" rev-parse refs/remotes/origin/dev)" ] \
  || die "local dev HEAD must exactly equal origin/dev"

intent_id="$(python3 -c 'import uuid; print(uuid.uuid4())')"
gate_runner="$control_root/infra/deploy/run_image_deployment_gate.sh"
context_helper="$control_root/infra/terraform/image_release_context.py"
[ -f "$context_helper" ] || die "Terraform release context helper is missing"
temporary="$(mktemp -d "${TMPDIR:-/tmp}/teamagent-image-plan.XXXXXXXX")"
cleanup() {
  rm -rf -- "$temporary"
}
trap cleanup EXIT
cd "$script_dir"
terraform state pull >"$temporary/state-before.json"
terraform plan \
  -input=false \
  -out="$plan_path" \
  -var="image_deployment_intent_id=$intent_id" \
  "$@"
terraform state pull >"$temporary/state-after.json"
[ "$(sha256sum "$temporary/state-before.json" | awk '{print $1}')" = \
  "$(sha256sum "$temporary/state-after.json" | awk '{print $1}')" ] \
  || die "Terraform state changed while the saved plan was being created"
python3 "$context_helper" capture \
  --terraform-dir "$script_dir" \
  --plan "$plan_path" \
  --output "$temporary/terraform-context.json"
bash "$gate_runner" prepare-deployment-intent \
  --plan "$plan_path" \
  --control-commit "$control_commit" \
  --terraform-context "$temporary/terraform-context.json"

echo "Saved image deployment plan prepared:"
echo "  plan=$plan_path"
echo "  intent_id=$intent_id"
echo "Apply only with: bash $script_dir/apply_image_release_plan.sh $plan_path"
